name: cbu_it_buddy
description: "A new Flutter project with IT support and game features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  # Cupertino icons for iOS-style UI elements
  cupertino_icons: ^1.0.8
  # Firebase for backend services (e.g., data storage)
  firebase_core: ^3.5.0
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.2
  # Markdown rendering for guides or documentation
  flutter_markdown: ^0.6.12
  # Flame for the game section with pixel-art characters
  flame: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting for code quality
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Updated assets section to include game and UI images
  assets:
  - lib/solution/
  - assets/images/
  